string = 'Curso em Vídeo Python'
print(string[9])
print(string[9:13])
print(string[9:21])
print(string[9:21:2])
print(string[:5])
print(string[15:])
print(string[9::3])
print(len(string))
print(string.count('o'))
print(string.count('o', 0, 13))
print(string.find('deo'))
print(string.find('Android'))
print('Curso' in string)
frase = string.replace('Python', 'Android')
print(frase)
frase = frase.upper()
print(frase)
frase = frase.lower().capitalize()
print(frase)
frase = frase.lower().title()
print(frase)
new = '   Aprenda Python   '
print(new.strip())
print(new)
lista = string.split()
print(string)
print(lista)
print('-'.join(lista))
print("""Oi estou testatndo vária linhas
      mais de uma linha para ser vista
      outra linha vamos conferir""")